### ISSUE TITLE
select example in the web demo takes really long

### ISSUE THREAD

**Issue by MangoIV** [polarity-lang/polarity-lang.github.io#9]
It appears, it reloads the entirety of the vscode, I think ideally it should literally just swap out the code example in the editor. I do not know if this is possible but I think it should be. Swapping out the examples takes long enough for an impatient me to think it's broken, so I'm expecting that other people would feel similar :P

**Comment by timsueberkrueb** [comment]
Just checked, the proposed solution above should work.
